openapi: 3.0.0
info:
  title: SubscriptionStoreApi
  version: 1.0.0
  description: API для управления подписками и пользователями
tags:
  - name: Subscriptions
    description: Подписки
  - name: Subscribers
    description: Подписки пользователей

components:
  schemas:
    Subscription:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор подписки
        name:
          type: string
          description: Название подписки
        price:
          type: number
          format: float
          description: Цена подписки
        paymentsCount:
          type: string
          description: Длительность подписки (например, "1 месяц", "3 месяца")
        isActive:
          type: boolean
          description: Статус подписки (активна/неактивна)
      required:
        - id
        - name
        - price
        - paymentsCount

    Subscriber:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор пользователя
        email:
          type: string
          format: email
          description: Электронная почта пользователя
        name:
          type: string
          description: Имя пользователя
        subscriptions:
          type: array
          items:
            $ref: '#/components/schemas/Subscription'
          description: Список подписок пользователя
      required:
        - id
        - email

paths:
  /api/v1/subscriptions:
    post:
      tags:
        - Subscriptions
      summary: Создает подписку
      operationId: createSubscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '201':
          description: Subscription created
    get:
      tags:
        - Subscriptions
      summary: Возвращает доступные подписки
      operationId: getSubscriptions
      responses:
        '200':
          description: A list of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'

  /api/v1/subscriptions/{subscriptionid}:
    get:
      tags:
        - Subscriptions
      summary: Возвращает доступную подписку
      operationId: getSubscription
      parameters:
        - name: subscriptionid
          in: path
          required: true
          description: Уникальный идентификатор подписки
          schema:
            type: string
      responses:
        '200':
          description: Subscription details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
    put:
      tags:
        - Subscriptions
      summary: Изменяет подписку
      operationId: updateSubscription
      parameters:
        - name: subscriptionid
          in: path
          required: true
          description: Уникальный идентификатор подписки
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '200':
          description: Subscription updated
    delete:
      tags:
        - Subscriptions
      summary: Удаляет подписку
      operationId: deleteSubscription
      parameters:
        - name: subscriptionid
          in: path
          required: true
          description: Уникальный идентификатор подписки
          schema:
            type: string
      responses:
        '204':
          description: Subscription deleted

  